--- 
before_script: 
  - "export CODE_COVERAGE_TOKEN=$CODE_COVERAGE_TOKEN"
install: 
  - "npm install"
language: node_js;
node_js: 
  - "11.10.1"
script: 
  - "npm run write-coveralls"
  - "npm test"

deploy:
provider: heroku
api_key: $HEROKU_TOKEN
app: cactus625
on: master
strategy: git
